name: build

on:
  push:
    branches:
      - main
  #schedule:
    # nightly build
    #- cron: "00 12 * * *"

jobs:
  build:
    runs-on: macos-latest
    env:
      CC: clang
      CXX: clang++
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      MACOSX_DEPLOYMENT_TARGET: 10.13
      EXTRA_CFLAGS: "-mmacosx-version-min=10.13"
      EXTRA_CXXFLAGS: "-mmacosx-version-min=10.13"
      EXTRA_LDFLAGS: "-mmacosx-version-min=10.13"
    steps:
    - name: Get current timestamp
      id: timestamp
      run: |
        echo "::set-output name=timestamp::$(date +%s)"
        echo "::set-output name=date::$(date +%Y%m%d)"

    - name: Get latest git tag
      id: git_tag
      uses: oprypin/find-latest-tag@v1
      with:
        repository: 'dafyk/mpv-macos-builds'
        releases-only: false

    - name: Get latest mpv git tag
      id: mpv_tag
      uses: oprypin/find-latest-tag@v1
      with:
        repository: 'mpv-player/mpv'
        releases-only: false

    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v1
      id: cpu-cores

    - name: Checkout mpv-player/mpv-build
      uses: actions/checkout@v2
      with:
        repository: 'mpv-player/mpv-build'
        fetch-depth: 0

    - name: Install dependencies
      run: |
        export MACOSX_DEPLOYMENT_TARGET="10.13"
        export EXTRA_CFLAGS="-mmacosx-version-min=10.13"
        export EXTRA_CXXFLAGS="-mmacosx-version-min=10.13"
        export EXTRA_LDFLAGS="-mmacosx-version-min=10.13"
        export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/opt/lib/pkgconfig:$PKG_CONFIG_PATH"
        brew update-reset
        brew update
        brew cleanup
        brew install -s rtmpdump
        find / -iname "librtmp.pc*"
