name: build

on: workflow_dispatch
  #push:
  #  branches:
  #    - main
  #schedule:
    # nightly build
    #- cron: "00 12 * * *"

jobs:
  build:
    name: Build mpv from source
    runs-on: macos-11
    env:
      CC: clang
      CXX: clang++
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      #HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      HOMEBREW_SDKROOT: "/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      MACOSX_DEPLOYMENT_TARGET: "10.13"
      SDKROOT: "/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      MACOS_SDK: "/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      SDK_PATH: "/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs"
      EXTRA_CFLAGS: "-mmacosx-version-min=10.13 -isysroot /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      EXTRA_CXXFLAGS: "-mmacosx-version-min=10.13 -isysroot /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      EXTRA_LDFLAGS: "-mmacosx-version-min=10.13 -isysroot /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      SWIFT_FLAGS: "-target x86_64-apple-macosx10.13"
      HOMEBREW_NO_COLOR: 1
      HOMEBREW_NO_EMOJI: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      HOMEBREW_NO_INSTALL_UPGRADE: 1
      HOMEBREW_BUILD_FROM_SOURCE: 1
      HOMEBREW_NO_INSTALL_FROM_API: 1
      
    steps:
      - name: Get current timestamp
        id: timestamp
        run: |
          echo "::set-output name=timestamp::$(date +%s)"
          echo "::set-output name=date::$(date +%Y%m%d)"

      - name: Get latest mpv git tag
        id: mpv_tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: 'mpv-player/mpv'
          releases-only: false

      - name: Checkout dafyk/mpv-macos-builds
        uses: actions/checkout@v3
        with:
          repository: 'dafyk/mpv-macos-builds'
          fetch-depth: 0
          submodules: true

      - name: Install MacOSX 10.14 SDK
        id: macossdk
        run: |
          # MacOSX10.14 SDK
          tar -C $SDK_PATH -xf MacOSX10.14.sdk.tar.xz
          sudo rm -rf $SDK_PATH/MacOSX11.3.sdk
          sudo mv $SDK_PATH/MacOSX.sdk $SDK_PATH/MacOSX11.3.sdk
          sudo ln -s $SDK_PATH/MacOSX10.14.sdk $SDK_PATH/MacOSX.sdk
          sudo /usr/libexec/PlistBuddy -c "Set :MinimumSDKVersion 10.14" /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Info.plist

      - name: Install Command Line Tools for Xcode 12.5.1
        id: macoscmdtools
        run: |
          # Command Line Tools for Xcode 12.5.1
          curl -ksJLO https://www.savero.net/Command_Line_Tools_for_Xcode_12.5.1.dmg
          sudo mv /Library/Developer/CommandLineTools /Library/Developer/CommandLineTools@13
          hdiutil attach Command_Line_Tools_for_Xcode_12.5.1.dmg
          cd /Volumes/Command\ Line\ Developer\ Tools/
          sudo installer -pkg Command\ Line\ Tools.pkg -target /
          sudo rm -rf /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
          sudo ln -s $SDK_PATH/MacOSX10.14.sdk /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk


      - name: Install Swift 4.x toolchain
        id: swift4
        run: |
          # Swift 4.x toolchain
          curl -ksJLO https://download.swift.org/swift-4.2.4-release/xcode/swift-4.2.4-RELEASE/swift-4.2.4-RELEASE-osx.pkg
          sudo installer -pkg swift-4.2.4-RELEASE-osx.pkg -target /
          #curl -ksJLO https://updates.cdn-apple.com/2019/cert/061-41823-20191025-5efc5a59-d7dc-46d3-9096-396bb8cb4a73/SwiftRuntimeForCommandLineTools.dmg
          #hdiutil attach SwiftRuntimeForCommandLineTools.dmg
          #sudo installer -pkg /Volumes/SwiftRuntimeForCommandLineTools/SwiftRuntimeForCommandLineTools.pkg -target /

      - name: Switch to Xcode 12.5.1
        id: xcode1251
        run: |
          # Switch to Xcode 12.5.1
          sudo xcode-select --reset
          sudo xcode-select -s /Applications/Xcode_12.5.1.app/Contents/Developer

      - name: Instal various mpv and ffmpeg dependencies using homebrew
        id: mpvffmpegdeps
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config http.postBuffer 524288000
          # Remove all bottled formulas
          brew uninstall $(brew list | grep -v -e git -e tar -e session-manager-plugin)
          #brew cleanup
          brew tap dafyk/mpv
          mkdir Bottles
          cd Bottles
          brew install --build-bottle dafyk/mpv/pkg-config
          brew bottle dafyk/mpv/pkg-config
          brew install --build-bottle dafyk/mpv/pkg-config
          brew bottle dafyk/mpv/pkg-config

          brew install --build-bottle dafyk/mpv/mpdecimal
          brew bottle dafyk/mpv/mpdecimal

          brew install --build-bottle dafyk/mpv/ca-certificates
          brew bottle dafyk/mpv/ca-certificates

          brew install --build-bottle dafyk/mpv/openssl@3
          brew bottle dafyk/mpv/openssl@3

          brew install --build-bottle dafyk/mpv/readline
          brew bottle dafyk/mpv/readline

          brew install --build-bottle dafyk/mpv/sqlite
          brew bottle dafyk/mpv/sqlite

          brew install --build-bottle dafyk/mpv/xz
          brew bottle dafyk/mpv/xz

          brew install --build-bottle dafyk/mpv/libffi
          brew bottle dafyk/mpv/libffi

          brew install --build-bottle dafyk/mpv/python@3.11
          brew bottle dafyk/mpv/python@3.11
          cd ..
          git add .
          git commit -m 'Added pkg-config homebrew bottle'
          git push
          exit 1
          # # Download taps from deus0ww and homebrew/core
          # brew tap dafyk/mpv
          # brew tap homebrew/core
          # brew cleanup --prune=all
          # brew update-reset
          # echo "next step: install dependencies"
          # brew install curl
          # brew reinstall -s $(brew deps --include-build -n dafyk/mpv/mpv) | :
          
          # # Disable installing formulas from bottles
          # #find $(brew --repository)/Library/Taps -type f -iname *rb -exec sed -i "" '/bottle do/,/end/c\' {} \;
          
          # # Force 10.13 deployment target for all homebrew formulas
          # #find $(brew --repository)/Library/Taps -type f -iname *rb -exec sed -i "" $'s/def install/def install\\\n    ENV["MACOSX_DEPLOYMENT_TARGET"] = "10.13"\\\n/' {} \;
          # #for dep in luajit python@3.8 python@3.10; do sed -i "" $'s/MacOS.version/"10.13"/' $(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula//$dep.rb;done
          # #for dep in luajit python@3.8 python@3.10 python@3.11; do find /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula -iname $dep.rb -exec sed -i "" $'s/MacOS.version/"10.13"/' {} +;done

          # # Patch formulas for 10.13 deployment
          # #patch -d$(brew --repository)/Library/Taps/deus0ww/homebrew-tap -p1 < mpv-deus0ww-patch.txt
          # #patch -d$(brew --repository)/Library/Taps/homebrew/homebrew-core -p1 < mpv-static-builds-patch.txt
          # #patch -d$(brew --repository)/Library/Taps/deus0ww/homebrew-tap -p0 < ffpmeg.rb.patch
          # #patch -d$(brew --repository)/Library/Taps/deus0ww/homebrew-tap -p0 < mpv.rb.patch
          # #patch -d$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/l -p0 < luajit.rb.patch
          # #patch -d$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/o -p0 < openssl@3.rb.patch
          # #patch -d$(brew --repository)/Library/Taps/deus0ww/homebrew-tap -p0 < libplacebo.rb.patch
          # #patch -d$(brew --repository)/Library/Taps/deus0ww/homebrew-tap -p0 < yt-dlp.rb.patch
          # #patch -d$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/c/ -p0 < cython.rb.patch
          # echo ${{ steps.mpv_tag.outputs.tag }}-${{ github.run_number }}>VERSION

          # # Disable all tests in formulas
          # # find $(brew --repository)/Library/Taps -type f -iname *rb -exec sed -i "" '/^  test do/,/^  end/c\' {} \;

          # #brew reinstall -v -s $(brew deps --include-build -n curl) curl $(brew deps --include-build -n deus0ww/tap/mpv | grep -v -e doxygen -e vulkan-headers -e glslang) deus0ww/tap/mpv || :
          # brew unlink dafyk/mpv/openssl@3 dafyk/mpv/dav1d
          # brew reinstall -v -s dafyk/mpv/mpv
          # echo "mpv build complete"

      - name: Build Apple Disk Image
        run: |
          mkdir /tmp/mpv-release
          cp -r /usr/local/Cellar/mpv/*/mpv.app /tmp/mpv-release
          rsync -avrz --no-links /usr/local/opt/ /tmp/mpv-release/lib2/
          cp ~/work/mpv-macos-builds/mpv-macos-builds/background.tiff /tmp/background.tiff
          cp ~/work/mpv-macos-builds/mpv-macos-builds/icon.icns /tmp/icon.icns
          cd /tmp/mpv-release
          brew install create-dmg dylibbundler
          dylibbundler -od -b -x ./mpv.app/Contents/MacOS/mpv -d ./mpv.app/Contents/libs/
          create-dmg --no-internet-enable --volname "mpv" --volicon "/tmp/icon.icns" --background "/tmp/background.tiff" --window-pos 200 120 --window-size 573 400 --icon-size 80 --icon "mpv.app" 200 175 --hide-extension "mpv.app" --app-drop-link 375 175 /tmp/mpv.dmg /tmp/mpv-release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.mpv_tag.outputs.tag }}-${{ github.run_number }}
          release_name: mpv build ${{ steps.mpv_tag.outputs.tag }}
          body: |
              - Build date: `${{ steps.timestamp.outputs.date }}`
              - Version: `${{ steps.mpv_tag.outputs.tag }} (commit: ${{ steps.mpv_tag.outputs.tag }})`
              - OS support: `macOS High Sierra 10.13 or later`
              - Workflow run number: `${{ github.run_number }}`
              - FFMPEG info:
              ```
              $\{\{ steps.build_mpv.outputs.FFMPEG_INFO \}\}
              ```
          draft: true
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/mpv.dmg
          asset_name: mpv-${{ steps.mpv_tag.outputs.tag }}-${{ github.run_number }}.dmg
          asset_content_type: application/x-apple-diskimage
