name: build

on:
  push:
    branches:
      - main
  #schedule:
    # nightly build
    #- cron: "00 12 * * *"

jobs:
  build:
    runs-on: macos-latest
    env:
      CC: clang
      CXX: clang++
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      MACOSX_DEPLOYMENT_TARGET: 10.13
      SDKROOT: "/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk"
      EXTRA_CFLAGS: "-mmacosx-version-min=10.13"
      EXTRA_CXXFLAGS: "-mmacosx-version-min=10.13"
      EXTRA_LDFLAGS: "-mmacosx-version-min=10.13"
      PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig:$PKG_CONFIG_PATH"
      LD_LIBRARY_PATH: "/usr/local/lib:$LD_LIBRARY_PATH"

    steps:
      - name: Checkout mpv-player/mpv
        uses: actions/checkout@v2
        with:
          repository: 'mpv-player/mpv'
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo xcode-select -s /Applications/Xcode_12.5.1.app/Contents/Developer
          export MACOSX_DEPLOYMENT_TARGET="10.13"
          export EXTRA_CFLAGS="-mmacosx-version-min=10.13"
          export EXTRA_CXXFLAGS="-mmacosx-version-min=10.13"
          export EXTRA_LDFLAGS="-mmacosx-version-min=10.13"
          export SDKROOT="/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk"
          brew update-reset
          for dep in $(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/*.rb; do sed -i "" $'s/def install/def install\\\n    ENV["MACOSX_DEPLOYMENT_TARGET"] = "10.13"\\\n/' $dep;done
          for dep in luajit python@3.8; do sed -i "" $'s/MacOS.version/"10.13"/' $(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula//$dep.rb;done

          brew uninstall --ignore-dependencies --force openssl
          brew uninstall --ignore-dependencies --force gnutls
          brew cleanup

          brew reinstall -s autoconf automake pkg-config libtool python freetype fribidi little-cms2 lua@5.1 libass ffmpeg meson

      - name: Build with meson
        run: |
          ./ci/build-macos.sh meson
        env:
          CC: "${{ matrix.cc }}"
          TRAVIS_OS_NAME: "${{ matrix.os }}"

      - name: Print meson log
        if: ${{ failure() }}
        run: |
          cat ./build/meson-logs/meson-log.txt
