name: build

on:
  push:
    branches:
      - main
  #schedule:
    # nightly build
    #- cron: "00 12 * * *"

jobs:
  build:
    runs-on: macos-latest
    env:
      CC: clang
      CXX: clang++
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      MACOSX_DEPLOYMENT_TARGET: 10.13
      EXTRA_CFLAGS: "-mmacosx-version-min=10.13"
      EXTRA_CXXFLAGS: "-mmacosx-version-min=10.13"
      EXTRA_LDFLAGS: "-mmacosx-version-min=10.13"
    steps:
    - name: Get current timestamp
      id: timestamp
      run: |
        echo "::set-output name=timestamp::$(date +%s)"
        echo "::set-output name=date::$(date +%Y%m%d)"

    - name: Get latest git tag
      id: git_tag
      uses: oprypin/find-latest-tag@v1
      with:
        repository: dafyk/mpv-macos-builds
        releases-only: false

    - name: Checkout mpv-player/mpv
      uses: actions/checkout@v2
      with:
        repository: 'mpv-player/mpv-build'
        fetch-depth: 0

    - name: Check upstream version
      id: upstream_tag
      run: |
        git fetch
        sed -i .bak 's/--dirty//g' version.sh
        echo "::set-output name=build_hash::$(sh version.sh)"

    - name: Install dependencies
      if: ${{ success() && steps.upstream_tag.outputs.build_hash != steps.git_tag.outputs.tag }}
      run: |
        ls -la
        mv VERSION VERSION.bak
        ./rebuild -j4

        mv version.sh.bak version.sh
        mkdir -p release
        cp -r build/mpv.app release
