name: build

on:
  push:
    branches:
      - main
  #schedule:
    # nightly build
    #- cron: "00 12 * * *"

jobs:
  build:
    runs-on: macos-latest
    env:
      CC: clang
      CXX: clang++
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      MACOSX_DEPLOYMENT_TARGET: 10.13
      SDKROOT: "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
      EXTRA_CFLAGS: "-mmacosx-version-min=10.13 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
      EXTRA_CXXFLAGS: "-mmacosx-version-min=10.13 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
      EXTRA_LDFLAGS: "-mmacosx-version-min=10.13 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
      PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig:$PKG_CONFIG_PATH"
      LD_LIBRARY_PATH: "/usr/local/lib:$LD_LIBRARY_PATH"

    steps:
      - name: Get current timestamp
        id: timestamp
        run: |
          echo "::set-output name=timestamp::$(date +%s)"
          echo "::set-output name=date::$(date +%Y%m%d)"

      - name: Get latest git tag
        id: git_tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: 'dafyk/mpv-macos-builds'
          releases-only: false

      - name: Get latest mpv git tag
        id: mpv_tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: 'mpv-player/mpv'
          releases-only: false

      - name: Checkout mpv-player/mpv
        uses: actions/checkout@v2
        with:
          repository: 'mpv-player/mpv'
          fetch-depth: 0

      - name: Install dependencies
        run: |
          git clone https://github.com/dafyk/mpv-macos-builds.git
          #sudo cp -a mpv-macos-builds/MacOSX10.4.sdk /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
          #sudo rm -rf /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
          #sudo ln -s /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.4.sdk /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
          #sudo rm -rf /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk
          #ls -la /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.4.sdk
          #sudo /usr/libexec/PlistBuddy -c "Set :MinimumSDKVersion 10.4" /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Info.plist

          sudo cp -a mpv-macos-builds/MacOSX10.4.sdk /Library/Developer/CommandLineTools/SDKs/
          sudo rm -rf /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
          sudo mv /Library/Developer/CommandLineTools/SDKs/MacOSX10.4.sdk /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk

          sudo chown -R root:wheel /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
          cd /Library/Developer/CommandLineTools/SDKs/
          sudo ln -s MacOSX.sdk MacOSX10.14.sdk
          sudo ln -s MacOSX.sdk MacOSX.sdk
          ls -la /Library/Developer/CommandLineTools/SDKs/
          #sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
          sudo xcode-select --reset
          sudo xcode-select -s /Library/Developer/CommandLineTools 
          echo "xcrun --sdk macosx10.14 --show-sdk-path -v"
          xcrun --sdk macosx10.14 --show-sdk-path -v
          echo "xcodebuild -version"
          xcodebuild -version
          exit 1
          cd -
          #sudo xcode-select -s /Applications/Xcode_12.5.1.app/Contents/Developer

          export MACOSX_DEPLOYMENT_TARGET="10.13"
          export EXTRA_CFLAGS="-mmacosx-version-min=10.13 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
          export EXTRA_CXXFLAGS="-mmacosx-version-min=10.13 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
          export EXTRA_LDFLAGS="-mmacosx-version-min=10.13 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
          #export SDKROOT="/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk"
          export SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
          brew update-reset
          for dep in $(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/*.rb; do sed -i "" $'s/def install/def install\\\n    ENV["MACOSX_DEPLOYMENT_TARGET"] = "10.13"\\\n/' $dep;done
          for dep in luajit python@3.8; do sed -i "" $'s/MacOS.version/"10.13"/' $(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula//$dep.rb;done

          brew uninstall --ignore-dependencies --force openssl
          brew uninstall --ignore-dependencies --force gnutls
          brew cleanup

          brew reinstall -s autoconf automake pkg-config libtool python freetype fribidi brotli little-cms2 lua@5.1 jpeg zimg libbluray libass ffmpeg meson
          # https://github.com/mpv-player/mpv/issues/10063#issuecomment-1092413762
          install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "/usr/local/opt/brotli/lib/libbrotlicommon.1.dylib" /usr/local/opt/brotli/lib/libbrotlidec.1.dylib
          install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "/usr/local/opt/brotli/lib/libbrotlicommon.1.dylib" /usr/local/opt/brotli/lib/libbrotlienc.1.dylib

      - name: Build with meson
        run: |
          echo "xcrun --show-sdk-path"
          xcrun --show-sdk-path
          echo "xcrun --find install_name_tool"
          xcrun --find install_name_tool
          echo "otool -L  /usr/bin/install_name_tool"
          otool -L  /usr/bin/install_name_tool
          curl -k https://www.savero.net/build-macos.patch --output ci/build-macos.patch
          patch -p1 ci/build-macos.sh < ci/build-macos.patch
          SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" ./ci/build-macos.sh waf
          python3 TOOLS/osxbundle.py build/mpv
          mkdir -p release
          cp -r build/mpv.app release

      - name: Build Apple Disk Image
        run: |
          #cd mpv
          brew install create-dmg
          create-dmg --sandbox-safe --no-internet-enable --volname "mpv" --app-drop-link 200 185 mpv.dmg release
          #rm -rf release/mpv.app
          mv mpv.dmg release/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.mpv_tag.outputs.tag }}
          release_name: mpv nightly build ${{ steps.timestamp.outputs.date }}
          body: |
              mpv nightly build
              build date: ${{ steps.timestamp.outputs.date }}
              version: ${{ steps.mpv_tag.outputs.tag }}
              OS support: macOS High Sierra 10.13 or later
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        if: ${{ success() && steps.mpv_tag.outputs.tag != steps.git_tag.outputs.tag }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/mpv.dmg
          asset_name: mpv-nightly-${{ steps.mpv_tag.outputs.tag }}.dmg
          asset_content_type: application/x-apple-diskimage
