name: build

on:
  push:
    branches:
      - main
  #schedule:
    # nightly build
    #- cron: "00 12 * * *"

jobs:
  build:
    runs-on: macos-latest
    env:
      CC: clang
      CXX: clang++
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      MACOSX_DEPLOYMENT_TARGET: 10.13
      EXTRA_CFLAGS: "-mmacosx-version-min=10.13"
      EXTRA_CXXFLAGS: "-mmacosx-version-min=10.13"
      EXTRA_LDFLAGS: "-mmacosx-version-min=10.13"
      PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig:$PKG_CONFIG_PATH"
      LD_LIBRARY_PATH: "/usr/local/lib:$LD_LIBRARY_PATH"

    steps:
    - name: Install dependencies
      run: |
        export MACOSX_DEPLOYMENT_TARGET="10.13"
        export EXTRA_CFLAGS="-mmacosx-version-min=10.13"
        export EXTRA_CXXFLAGS="-mmacosx-version-min=10.13"
        export EXTRA_LDFLAGS="-mmacosx-version-min=10.13"
        export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
        brew update-reset
        brew list
